spring.application.name=user-registry-core-api


#database configuration H2
spring.datasource.url=jdbc:h2:mem:user-registry-database
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=admin
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true


# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.baseline-on-migrate=true